### ISSUE TITLE
Please update the itoa dependency

### ISSUE THREAD

**Issue by RalfJung** [bcmyers/num-format#29]
itoa 0.4, a dependency of this crate, uses the deprecated `mem::uninitialized` function. On recent nightly builds of the compiler, that function has become a lot slower in order to mitigate the many ways in which it is used incorrectly throughout the ecosystem. We'd like to move even further and add future-compatibility warnings against `mem::uninitialized`, which would show up everywhere that itoa is in the dependency tree.

This is one of the most popular crates that still depends on itoa 0.4. To fix the performance regression and to avoid future-compat warnings showing up for users of this crate, it'd be great if an update of this crate could be released that bumps the dependency to itoa 1.0.

**Comment by LovecraftianHorror** [comment]
I'm not sure if this crate is maintained anymore #21 #27

---

_All of this is from memory_

The main dependent is `inferno` which had a very simple usage for it (I think just formatting an integer with commas for thousands separators)

`tokei` has a bit more complicated of a usage depending on what compatibility it wants to keep since it used a formatter that respected localization

And I hadn't looked into `ss58-registry`, but those cover the top three most downloaded dependents according to crates.io which are also the only ones that have >100,000 downloads

**Comment by niklasha** [comment]
I spent an hour or two on updating dependencies in [my fork](https://github.com/niklasha/num-format) just now, if it is of any help.

**Comment by bcmyers** [comment]
Hi all. Apologies for abandoning this crate for so long. I just picked up maintenance again and have published a new version (0.4.2) on crates.io with updated 3rd party deps and `mem::uninitialized` has been removed.
