### ISSUE TITLE
Maybe refactor error types

### ISSUE THREAD

**Issue by bcmyers** [bcmyers/num-format#3]

**Comment by BurntSushi** [comment]
Since `failure` is a public dependency, you might consider dropping it. While the future is a bit unclear, I'm pretty sure it doesn't involve `failure 0.1`, so dropping it now will be easier for you than dropping it later. I don't think you need to replace it with anything either. You don't have that many error types, so writing out the impls by hand shouldn't be a burden.

(You might also consider flattening your module structure. A deeply nested crate with such a small API doesn't seem worth it IMO.)

**Comment by loewenheim** [comment]
Is there a reason apart from `failure` that `Error` and `ErrorKind` are distinct types?

**Comment by BurntSushi** [comment]
Splitting Error and ErrorKind is a very common pattern because it permits flexibility on the internal representation of an Error.

**Comment by bcmyers** [comment]
@BurntSushi - I agree with both of your suggestions. Thanks for the input! Here's a commit that flattens the module hierarchy (a breaking change, but better to get it over with early): [link](https://github.com/bcmyers/num-format/commit/4b222f5849522e72696efd08c80a24410262a36d). I'll also factor out `failure`
